###
POST http://localhost:5000/api/users
Content-type: application/json

{
  "name":"sophia",
  "email":"sophia@gmail.com",
  "password": "sophia"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
 "email":"sophia@gmail.com",
  "password": "sophia"
}
###
GET http://localhost:5000/api/users